FROM quay.io/signalfuse/collectd:latest

# Disable everything we can except elasticsearch
ENV COLLECTD_INTERVAL=3 COLLECTD_HOSTNAME=couchdb-test DISABLE_AGGREGATION=true DISABLE_CPU=true DISABLE_CPUFREQ=true DISABLE_DF=true DISABLE_DISK=true DISABLE_DOCKER=true DISABLE_HOST_MONITORING=true DISABLE_INTERFACE=true DISABLE_LOAD=true DISABLE_MEMORY=true DISABLE_PROTOCOLS=true DISABLE_VMEM=true DISABLE_UPTIME=true

# Debian is super minimalistic
RUN apt-get update &&\
    apt-get install -yq netcat curl

CMD /.docker/setup_couchdb
ADD integration_test/setup_couchdb /.docker/setup_couchdb
RUN chmod +x /.docker/setup_couchdb

# ## The context of the image build should be the root dir of this repo!!
ADD integration_test/collectd.conf /etc/collectd/
ADD couchdb_plugin.py /opt/collectd-couchdb/
ADD couchdb_metrics.py /opt/collectd-couchdb/
ADD sfx_collectd_utilities.py /opt/collectd-couchdb/
ADD urllib_ssl_handler.py /opt/collectd-couchdb/
ADD integration_test/20-couchdb-test.conf /etc/collectd/managed_config/
