version: '2'
services:
  collectd:
    build:
      context: ..
      dockerfile: integration_test/Dockerfile.collectd
    environment:
      SF_API_TOKEN: testing
      SF_INGEST_TOKEN: fake_sfx
    depends_on:
      - fake_sfx
      - couchdb210

  couchdb210:
    image: couchdb:2.1
    ports:
      - 5984

  fake_sfx:
    build:
      context: .
      dockerfile: Dockerfile.sink

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
        - collectd
